version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Etc/UTC"
    groups:
      pre-commit:
        patterns:
          - "*"
