name: Test action

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"
      - "!dependabot/**"

permissions:
  contents: read

# Group runs by workflow and PR/ref. Cancel an older run when a new one uses the same group.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}${{ github.event_name == 'release' && '-release' || '' }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest, windows-2022, windows-latest, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Bats and Bats libraries
        uses: ./

      - name: Download Bats library sources
        id: sources
        shell: bash
        run: |
          set -eu

          source_path="$(mktemp -d)"
          echo "path=$source_path" >> "$GITHUB_OUTPUT"

          ./download-bats-repos.sh "$source_path"

      - name: Test bats-support
        shell: bash
        env:
          SOURCE_PATH: ${{ steps.sources.outputs.path }}
        run: bats "$SOURCE_PATH/bats-support/test"

      - name: Test bats-assert
        shell: bash
        env:
          SOURCE_PATH: ${{ steps.sources.outputs.path }}
        run: bats "$SOURCE_PATH/bats-assert/test"

      - name: Test bats-detik
        continue-on-error: ${{ runner.os == 'macOS' }}
        shell: bash
        env:
          SOURCE_PATH: ${{ steps.sources.outputs.path }}
        run: bats "$SOURCE_PATH/bats-detik/tests"

      - name: Test bats-file
        continue-on-error: true
        shell: bash
        env:
          SOURCE_PATH: ${{ steps.sources.outputs.path }}
        run: bats "$SOURCE_PATH/bats-file/test"

      - name: Test action examples
        shell: bash
        run: bats -T -p tests

  super-linter:
    name: Run Super-Linter
    uses: bats-hardened/.github/.github/workflows/super-linter.yml@44fd251ecb1b4ca6fd2537eaa65be75b9be0395d # v1.1.1-beta01
    permissions:
      contents: read
